### ISSUE TITLE
TransactionTooLargeException

### ISSUE THREAD

**Issue by bboralRMN** [RoverPlatform/rover-android#131]
When an experience is put in the background (for example, by clicking an external link), the SDK will cause the host app to crash with the below exception. This is observed on extremely large Rover experiences. 

```
06-09 08:12:34.466 2529-2529/system_process W/InputMethodManagerService: Session failed to close due to remote exception
                                                                         android.os.DeadObjectException
                                                                             at android.os.BinderProxy.transactNative(Native Method)
                                                                             at android.os.BinderProxy.transact(Binder.java:503)
                                                                             at com.android.internal.view.IInputMethodSession$Stub$Proxy.finishSession(IInputMethodSession.java:305)
                                                                             at com.android.server.InputMethodManagerService.finishSessionLocked(InputMethodManagerService.java:1580)
                                                                             at com.android.server.InputMethodManagerService.clearClientSessionLocked(InputMethodManagerService.java:1571)
                                                                             at com.android.server.InputMethodManagerService.clearCurMethodLocked(InputMethodManagerService.java:1597)
                                                                             at com.android.server.InputMethodManagerService.onServiceDisconnected(InputMethodManagerService.java:1616)
                                                                             at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:1228)
                                                                             at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1242)
                                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at com.android.server.SystemServer.run(SystemServer.java:283)
                                                                             at com.android.server.SystemServer.main(SystemServer.java:168)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-09 08:12:34.467 2529-2540/system_process I/ActivityManager: Process com.android.inputmethod.latin (pid 5818) has died
06-09 08:12:34.468 2529-2540/system_process W/ActivityManager: Scheduling restart of crashed service com.android.inputmethod.latin/.LatinIME in 1000ms
06-09 08:12:34.471 2529-2529/system_process W/InputMethodManagerService: Session failed to close due to remote exception
                                                                         android.os.DeadObjectException
                                                                             at android.os.BinderProxy.transactNative(Native Method)
                                                                             at android.os.BinderProxy.transact(Binder.java:503)
                                                                             at com.android.internal.view.IInputMethodSession$Stub$Proxy.finishSession(IInputMethodSession.java:305)
                                                                             at com.android.server.InputMethodManagerService.finishSessionLocked(InputMethodManagerService.java:1580)
                                                                             at com.android.server.InputMethodManagerService.clearClientSessionLocked(InputMethodManagerService.java:1571)
                                                                             at com.android.server.InputMethodManagerService.clearCurMethodLocked(InputMethodManagerService.java:1597)
                                                                             at com.android.server.InputMethodManagerService.onServiceDisconnected(InputMethodManagerService.java:1616)
                                                                             at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:1228)
                                                                             at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1242)
                                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at com.android.server.SystemServer.run(SystemServer.java:283)
                                                                             at com.android.server.SystemServer.main(SystemServer.java:168)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-09 08:12:34.477 2529-4250/system_process W/InputMethodManagerService: Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@923a4d2 (uid=10019 pid=8297)
```

**Comment by chrisrecalis** [comment]
Hey @bboralRMN just curious as to when you are seeing this. Is it after you visit a lot of screens or will the error be thrown on the first screen?

We used to save the entire experience into the state but realized it was too large. So our approach was to just rely on fetching the experience again. The following commit made this change
https://github.com/RoverPlatform/rover-android/commit/ba88850cef321abf37edb1c78b8158b366f7b368

**Comment by bboralRMN** [comment]
It can happen on the first screen or multiple screens deep. The key point is that we saw this on extremely large experiences (those whose JSON > ~300kb).

**Comment by chrisrecalis** [comment]
@bboralRMN do you have any steps you could share to reproduce this? I have loaded a 1.6MB experience and haven't been able to get this exception. I also have the developer setting `Don't keep activities` on which should trigger a TransactionTooLargeException error immediately

**Comment by bboralRMN** [comment]
Let me work on getting you steps to reproduce.

**Comment by chrisrecalis** [comment]
@bboralRMN I've identified the issue. Thanks for the reproducible steps! The issue wasn't the overall size of the experience but the size of an individual screen which caused the crash
