### ISSUE TITLE
Notification Center list view crash

### ISSUE THREAD

**Issue by orospakr** [RoverPlatform/rover-android#308]
Rover 2.2.3.

```
2018-11-26 12:22:28.768 23851-23851/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: [REDACTED], PID: 23851
    java.lang.IllegalStateException: imageView must not be null
        at io.rover.notifications.ui.NotificationItemView.bindThumbnail(NotificationItemView.kt:67)
        at io.rover.notifications.ui.NotificationItemView$viewModel$2$1.invoke(NotificationItemView.kt:43)
        at io.rover.notifications.ui.NotificationItemView$viewModel$2$1.invoke(NotificationItemView.kt:23)
        at io.rover.core.streams.Operators$subscribe$1.onNext(Operators.kt:28)
        at io.rover.core.streams.Operators$takeUntil$1$1.onNext(Operators.kt:923)
        at io.rover.core.streams.Operators$flatMap$1$sourceSubscriber$1$onNext$transformSubscriber$1.onNext(Operators.kt:185)
        at io.rover.core.streams.Publishers$just$1$1.request(Publishers.kt:22)
        at io.rover.core.streams.Operators$flatMap$1$sourceSubscriber$1$onNext$transformSubscriber$1.onSubscribe(Operators.kt:191)
        at io.rover.core.streams.Publishers$just$1.subscribe(Publishers.kt:15)
        at io.rover.core.streams.Operators$flatMap$1$sourceSubscriber$1.onNext(Operators.kt:196)
        at io.rover.core.streams.Schedulers$observeOn$1$1$onNext$1.invoke(Schedulers.kt:55)
        at io.rover.core.streams.Schedulers$observeOn$1$1$onNext$1.invoke(Schedulers.kt:40)
        at io.rover.core.streams.Schedulers$sam$java_lang_Runnable$0.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6703)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
```

**Comment by orospakr** [comment]
This was a customer integration issue.
