### ISSUE TITLE
Timeouts occurring in Asset Service.

### ISSUE THREAD

**Issue by orospakr** [RoverPlatform/rover-android#323]
```
Fatal Exception: java.lang.Exception: Reached timeout while blocking for publisher! Items received: 0
      at io.rover.core.streams.Operators.blockForResult(Operators.kt:1123)
      at io.rover.core.streams.Operators.blockForResult$default(Operators.kt:1096)
      at io.rover.core.assets.AssetRetrievalStage.request(AssetRetrievalStage.kt:26)
      at io.rover.core.assets.AssetRetrievalStage.request(AssetRetrievalStage.kt:15)
      at io.rover.core.assets.DecodeToBitmapStage.request(DecodeToBitmapStage.kt:18)
      at io.rover.core.assets.DecodeToBitmapStage.request(DecodeToBitmapStage.kt:14)
      at io.rover.core.assets.InMemoryBitmapCacheStage$lruCache$1.create(InMemoryBitmapCacheStage.kt:47)
      at io.rover.core.assets.InMemoryBitmapCacheStage$lruCache$1.create(InMemoryBitmapCacheStage.kt:42)
      at android.util.LruCache.get(LruCache.java:132)
      at io.rover.core.assets.InMemoryBitmapCacheStage.request(InMemoryBitmapCacheStage.kt:57)
      at io.rover.core.assets.InMemoryBitmapCacheStage.request(InMemoryBitmapCacheStage.kt:14)
      at io.rover.core.assets.BitmapWarmGpuCacheStage.request(BitmapWarmGpuCacheStage.kt:15)
      at io.rover.core.assets.AndroidAssetService$getImageByUrl$1.invoke(AndroidAssetService.kt:67)
      at io.rover.core.assets.AndroidAssetService$getImageByUrl$1.invoke(AndroidAssetService.kt:22)
      at io.rover.core.streams.Publishers$defer$1.subscribe(Publishers.kt:195)
      at io.rover.core.streams.Operators$subscribeOn$2$1.invoke(Operators.kt:1026)
      at io.rover.core.streams.Operators$subscribeOn$2$1.invoke(Unknown Source)
      at io.rover.core.streams.Schedulers$sam$java_lang_Runnable$0.run(Unknown Source:2)
      at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
      at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
      at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1152)
      at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1990)
      at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1938)
      at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by orospakr** [comment]
Hypothesis:

* HTTP fetch does never times out and delivers an error type for it, and the publisher blockFoResult() being used in AssetRetrievalStage method hits its hard exception-throwing timeout.
